draw_config:
  key_w: 60.0
  key_h: 56.0
  split_gap: 30.0
  combo_w: 32.0
  combo_h: 32.0
  key_rx: 6.0
  key_ry: 6.0
  n_columns: 1
  separate_combo_diagrams: false
  combo_diagrams_scale: 2
  inner_pad_w: 3.0
  inner_pad_h: 3.0
  outer_pad_w: 30.0
  outer_pad_h: 56.0
  line_spacing: 1.2
  arc_radius: 6.0
  append_colon_to_layer_header: false
  small_pad: 2.0
  legend_rel_x: 0.0
  legend_rel_y: 0.0
  draw_key_sides: false
  key_side_pars:
    rel_x: 0
    rel_y: 4
    rel_w: 12
    rel_h: 12
    rx: 4
    ry: 4
  svg_style: |
    /* inherit to force styles through use tags */
    svg path {
        fill: inherit;
    }

    /* font and background color specifications */
    svg.keymap {
        font-family: SFMono-Regular,Consolas,Liberation Mono,Menlo,monospace;
        font-size: 14px;
        font-kerning: normal;
        text-rendering: optimizeLegibility;
        fill: #24292e;
    }

    /* default key styling */
    rect.key {
        fill: #f6f8fa;
        stroke: #c9cccf;
        stroke-width: 1;
    }

    /* default key side styling, only used is draw_key_sides is set */
    rect.side {
        filter: brightness(90%);
    }

    /* color accent for combo boxes */
    rect.combo, rect.combo-separate {
        fill: #c1efff;
        stroke: white;
        stroke-width: 2;
    }

    /* color accent for held keys */
    rect.held, rect.combo.held {
        fill: #FFA066;
    }

    /* color accent for ghost (optional) keys */
    rect.ghost, rect.combo.ghost {
        stroke-dasharray: 4, 4;
        stroke-width: 2;
    }

    text {
        text-anchor: middle;
        dominant-baseline: middle;
    }

    /* styling for layer labels */
    text.label {
        font-weight: bold;
        text-anchor: start;
        fill: inherit;
        text-transform: uppercase;
        font-size: 19px;
    }

    /* styling for combo tap, and key hold/shifted label text */
    text.combo, text.hold, text.shifted {
        font-size: 10px;
    }

    text.hold {
        text-anchor: middle;
        dominant-baseline: auto;
    }

    text.shifted {
        text-anchor: middle;
        dominant-baseline: hanging;
    }

    /* styling for hold/shifted label text in combo box */
    text.combo.hold, text.combo.shifted {
        font-size: 8px;
    }

    /* lighter symbol for transparent keys */
    text.trans {
        fill: #7b7e81;
    }

    /* styling for combo dendrons */
    path.combo {
        stroke-width: 1;
        stroke: gray;
        fill: none;
    }

    /* Start Tabler Icons Cleanup */
    /* cannot use height/width with glyphs */
    .icon-tabler > path {
        fill: inherit;
        stroke: inherit;
        stroke-width: 2;
    }
    /* hide tabler's default box */
    .icon-tabler > path[stroke="none"][fill="none"] {
        visibility: hidden;
    }
    /* End Tabler Icons Cleanup */
  svg_extra_style: ''
  shrink_wide_legends: 4
  glyph_tap_size: 14
  glyph_hold_size: 12
  glyph_shifted_size: 10
  glyphs: {}
  glyph_urls:
    tabler: https://unpkg.com/@tabler/icons/icons/{}.svg
    mdi: https://raw.githubusercontent.com/Templarian/MaterialDesign-SVG/master/svg/{}.svg
    mdil: https://raw.githubusercontent.com/Pictogrammers/MaterialDesignLight/master/svg/{}.svg
    material: https://fonts.gstatic.com/s/i/short-term/release/materialsymbolsoutlined/{}/default/48px.svg
  use_local_cache: true
parse_config:
  preprocess: true
  skip_binding_parsing: false
  raw_binding_map: {
    "&TREM E": "Ë",
    "&TREM I": "Ï",
    "&TREM O": "Ö",
    "&TREM U": "Ü",
    "&A_GR": "À",
    "&A_CI": "Â",
    # "&hrme SL 0": "È",
    # "&hrmi SL 0": "Î",
    "&E_GR": "È",
    "&CIRC E": "Ê",
    "&E_CU": "É",
    "&I_CI": "Î",
    "&O_CI": "Ô",
    "&U_CI": "Û",
    "&U_GR": "Ù",
    "&CEDIL": "Ç",
    "&KPD ACC_TR": "¨",
    "&KPD ACC_GR": "`",
    "&KPD ACC_CI": "^",
    "&kp QUEST": "?",
    "&kp RA(COMMA)": "<",
    "&kp RA(DOT)": ">",
    "&GRA": "`",
    "&CAR": "^",
    "&kp LBRAC": "{",
    "&kp RBRAC": "}",
    "&kp LBKET": "[",
    "&kp RBKET": "]",
    "&kp PIP": "|",
    "&laquo": "«",
    "&raquo": "»",
    "&math_1_4": "¼",
    "&math_1_2": "½",
    "&math_3_4": "¾",
    "&math_pm": "±",
    "&kp DEG": "°",
    "&kp RA(RBKT)": "~",
    "&kp SLSH": "/",
    "&math_micro": "µ",
    "&mkp LCLK": "LEFT CLICK",
    "&mkp RCLK": "RIGHT CLICK",
    "&mwh SCROLL_LEFT": "SCROLL LEFT",
    "&mwh SCROLL_RIGHT": "SCROLL RIGHT",
    "&mwh SCROLL_UP": "SCROLL UP",
    "&mwh SCROLL_DOWN": "SCROLL DOWN",
    "&mmv MOVE_LEFT": "CURSOR LEFT",
    "&mmv MOVE_RIGHT": "CURSOR RIGHT",
    "&mmv MOVE_UP": "CURSOR UP",
    "&mmv MOVE_DOWN": "CURSOR DOWN",
    "&mwh_tg": "TOGGLE SCROLL",
    "&caps_word": "CAPS WORD",
    "&caps_lock": "CAPS LOCK",
    "&kp LC(X)": "CUT",
    "&kp LC(C)": "COPY",
    "&kp LC(V)": "PASTE",
    "&kp LC(LA(J))": "TMUX",
    "&TMUX_SESSION": "TMUX  NEW SESSION",
    "&TMUX_CMD": "TMUX COMMAND",
    "&LTE": " <= ",
    "&GTE": " >= ",
    "&ARROW": " -> ",
    "&FAT_ARROW": " => "
    }
  sticky_label: sticky
  toggle_label: toggle
  trans_legend:
    t: ▽
    type: trans
  mark_alternate_layer_activators: true
  qmk_remove_keycode_prefix:
  - KC_
  qmk_keycode_map:
    XXXXXXX: ''
    'NO': ''
    MINUS: '-'
    MINS: '-'
    EQUAL: '='
    EQL: '='
    LEFT_BRACKET: '['
    LBRC: '['
    RIGHT_BRACKET: ']'
    BACKSLASH: \
    BSLS: \
    NONUS_HASH: '#'
    NUHS: '#'
    SEMICOLON: ;
    SCLN: ;
    QUOTE: ''''
    QUOT: ''''
    GRAVE: '`'
    GRV: '`'
    COMMA: ','
    COMM: ','
    DOT: .
    SLASH: /
    SLSH: /
    TILDE: '~'
    TILD: '~'
    EXCLAIM: '!'
    EXLM: '!'
    AT: '@'
    HASH: '#'
    DOLLAR: $
    DLR: $
    PERCENT: '%'
    PERC: '%'
    CIRCUMFLEX: ^
    CIRC: ^
    AMPERSAND: '&'
    AMPR: '&'
    ASTERISK: '*'
    ASTR: '*'
    LEFT_PAREN: (
    LPRN: (
    RIGHT_PAREN: )
    RPRN: )
    UNDERSCORE: _
    UNDS: _
    PLUS: +
    LEFT_CURLY_BRACE: '{'
    LCBR: '{'
    RIGHT_CURLY_BRACE: '}'
    RCBR: '}'
    PIPE: '|'
    COLON: ':'
    COLN: ':'
    DOUBLE_QUOTE: '"'
    DQUO: '"'
    DQT: '"'
    LEFT_ANGLE_BRACKET: <
    LABK: <
    LT: <
    RIGHT_ANGLE_BRACKET: '>'
    RABK: '>'
    GT: '>'
    QUESTION: '?'
    QUES: '?'
  zmk_remove_keycode_prefix: []
  zmk_keycode_map:
    EXCLAMATION: '!'
    EXCL: '!'
    AT_SIGN: '@'
    AT: '@'
    HASH: '#'
    POUND: '#'
    DOLLAR: $
    DLLR: $
    PERCENT: '%'
    PRCNT: '%'
    CARET: ^
    AMPERSAND: '&'
    AMPS: '&'
    ASTERISK: '*'
    ASTRK: '*'
    STAR: '*'
    LEFT_PARENTHESIS: (
    LPAR: (
    RIGHT_PARENTHESIS: )
    RPAR: )
    EQUAL: '='
    PLUS: +
    MINUS: '-'
    UNDERSCORE: _
    UNDER: _
    SLASH: /
    FSLH: /
    QUESTION: '?'
    QMARK: '?'
    BACKSLASH: \
    BSLH: \
    PIPE: '|'
    NON_US_BACKSLASH: \
    PIPE2: '|'
    NON_US_BSLH: '|'
    SEMICOLON: ;
    SEMI: ;
    COLON: ':'
    SINGLE_QUOTE: ''''
    SQT: ''''
    APOSTROPHE: ''''
    APOS: ''''
    DOUBLE_QUOTES: '"'
    DQT: '"'
    COMMA: ','
    LESS_THAN: <
    LT: <
    PERIOD: .
    DOT: .
    GREATER_THAN: '>'
    GT: '>'
    LEFT_BRACKET: '['
    LBKT: '['
    LEFT_BRACE: '{'
    LBRC: '{'
    RIGHT_BRACKET: ']'
    RBKT: ']'
    RIGHT_BRACE: '}'
    RBRC: '}'
    GRAVE: '`'
    TILDE: '~'
    NON_US_HASH: '#'
    NUHS: '#'
    TILDE2: '~'
    RET: 'RETURN'
    BSPC: 'BACK SPACE'
    PRINTSCREEN: 'PRINT SCREEN'
    SLCK: 'SCROLL LOCK'
    INS: 'INSERT'
    PG_UP: 'PAGE UP'
    PG_DN: 'PAGE DOWN'
    LALT: 'ALT'
    LGUI: 'GUI'
    LSHFT: 'SHIFT'
    LCTRL: 'CTRL'
  zmk_combos:
    combo_capsword:
      draw_separate: true
    combo_capslock:
      draw_separate: true
    combo_tmux:
      draw_separate: true
    combo_tmux_session:
      draw_separate: true
    combo_tmux_cmd:
      draw_separate: true
    combo_tab:
      align: "bottom"
      offset: 0.3
    combo_tab_34:
      align: "bottom"
      offset: 0.3
